spring:
  cache:
    type: redis
  redis:  #redis
    database: 1
    host: localhost
    port: 6379
    password: 
    jedis:
      pool:
        max-active: 8
        max-wait: -1
        max-idle: 8
        min-idle: 0
    timeout: 500
  data:
    elasticsearch: #elasticsearch
      cluster-name: elasticsearch_psy
      cluster-nodes: 127.0.0.1:9300  #java客户端Port9300
      repositories:
        enabled: true
    mongodb:  #mongodb
      database: testMongodb
      host: localhost
      port: 27017